<Project>
  <PropertyGroup>
    <Company>AAG</Company>
    <Authors>AAG</Authors>
    <Product>Simple Job Runner</Product>
    <Version>0.3.1</Version>
    <AssemblyVersion>0.3.1.0</AssemblyVersion>
    <FileVersion>0.3.1.0</FileVersion>
    <RepositoryUrl>https://github.com/aagaag/windows-simple-job-runner</RepositoryUrl>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
